options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: previewbuild

steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - gcr.io/$PROJECT_ID/previewbuild:$COMMIT_SHA
      - --builder
      - gcr.io/buildpacks/builder:latest
      - --network
      - cloudbuild

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "previewbuild"
      - "--image"
      - "gcr.io/$PROJECT_ID/previewbuild:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/previewbuild:$COMMIT_SHA"
