options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}

projectId: previewbuild
steps:
  #build the container
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/previewbuild/ryann-repo/pr-$_PR_NUMBER:$SHORT_SHA",
        ".",
        "-f",
        "Dockerfile",
      ]

  #push the container to the container registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/previewbuild/ryann-repo/pr-$_PR_NUMBER:$SHORT_SHA",
      ]

  #deploy the container to a PR-specific cloud run service
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "pr-$_PR_NUMBER",
        "--image",
        "us-central1-docker.pkg.dev/previewbuild/ryann-repo/pr-$_PR_NUMBER:$SHORT_SHA",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--port",
        "80",
        "--labels=pr=$_PR_NUMBER,commit=$SHORT_SHA",
        "--service-account=preview-builds@previewbuild.iam.gserviceaccount.com",
        "--memory=512Mi",
        "--cpu=1",
        "--concurrency=80",
        "--min-instances=0",
        "--max-instances=1",
        "--set-env-vars=PR_NUMBER=$_PR_NUMBER,COMMIT_SHA=$SHORT_SHA",
      ]
    id: deploy

  # Post Cloud Run URL to GitHub PR
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        # Install jq
        apt-get update -y && apt-get install -y jq

        # Get the Cloud Run URL for this specific PR instance
        CLOUD_RUN_URL=$$(gcloud run services describe pr-$_PR_NUMBER --region us-central1 --format='value(status.url)')
        echo "Cloud Run URL for PR #$_PR_NUMBER: $$CLOUD_RUN_URL"

        # Check for existing comments on the PR
        if [ -n "$_PR_NUMBER" ]; then
          EXISTING_COMMENTS=$$(curl -s \
            -H "Authorization: Bearer $$GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rechandler/previewbuild/issues/$_PR_NUMBER/comments)
          
          # Check if any comment contains our deployment message
          if echo "$$EXISTING_COMMENTS" | grep -q "Preview deployment is ready!"; then
            echo "Found existing preview deployment comment"
            # Delete existing preview deployment comment
            COMMENT_ID=$$(echo "$$EXISTING_COMMENTS" | jq -r '.[] | select(.body | contains("Preview deployment is ready!")) | .id')
            curl -X DELETE \
              -H "Authorization: Bearer $$GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/rechandler/previewbuild/issues/comments/$$COMMENT_ID
            echo "Deleted existing preview deployment comment"
          fi
        fi

        # Post comment to GitHub PR with the PR-specific URL
        curl -X POST \
          -H "Authorization: Bearer $$GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/rechandler/previewbuild/issues/$_PR_NUMBER/comments \
          -d "{\"body\":\"🚀 Preview deployment for PR #$_PR_NUMBER (Commit: $SHORT_SHA) is ready!\n\n🔗 **Preview URL**: $$CLOUD_RUN_URL\n\n_This preview environment will be automatically deleted when the PR is closed._\"}"
    secretEnv: ["GITHUB_TOKEN"]
    waitFor: ["deploy"] # Wait for deployment to complete

images:
  - us-central1-docker.pkg.dev/previewbuild/ryann-repo/pr-$_PR_NUMBER:$SHORT_SHA

# Secret for GitHub token
availableSecrets:
  secretManager:
    - versionName: projects/previewbuild/secrets/github_token/versions/latest
      env: "GITHUB_TOKEN"
