options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: previewbuild

steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - previewbuild
      - --builder
      - gcr.io/buildpacks/builder:latest
      - --network
      - cloudbuild

images:
  - "gcr.io/previewbuild/previewbuild:$COMMIT_SHA"
