options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: previewbuild

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/previewbuild:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/previewbuild:$COMMIT_SHA"]

  # Verify image exists
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Verifying image exists..."
        gcloud container images describe gcr.io/$PROJECT_ID/previewbuild:$COMMIT_SHA

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "previewbuild"
      - "--image"
      - "gcr.io/$PROJECT_ID/previewbuild:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/previewbuild:$COMMIT_SHA"

timeout: "1800s"
