options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: previewbuild
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/previewbuild/ryann-repo/my-app:latest",
        ".",
        "-f",
        "Dockerfile",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/previewbuild/ryann-repo/my-app"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "my-app",
        "--image",
        "us-central1-docker.pkg.dev/previewbuild/ryann-repo/my-app:latest",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--port",
        "80",
      ]
images:
  - us-central1-docker.pkg.dev/previewbuild/ryann-repo/my-app
