  options:
    logging: CLOUD_LOGGING_ONLY
    pool: {}
  projectId: previewbuild


  steps:
  - name: gcr.io/buildpacks/builder
    entrypoint: pack
    args:
    - build
    - global
    - --builder
    - gcr.io/buildpacks/builder:latest
    - --network
    - cloudbuild
  images:
  - global

-docker.pkg.dev/previewbuild

/rechandler/previewbuild

/gcr.io/previewbuild/github.com/rechandler/previewbuild:$COMMIT_SHA
