[[build.env]]
name = "BP_NODE_RUN_SCRIPTS"
value = "build"

[[build.env]]
name = "BP_LAUNCHPOINT"
value = "index.js"

[[build.env]]
name = "BP_WEB_SERVER"
value = "false"

[[build.env]]
name = "NODE_VERBOSE"
value = "true" 